WIP:Adding build doc step
biodatageeks/pysequila pull request #17
Opened 2020-10-15 17:35 UTC by mwiewior

2020-10-16 11:52 UTC, agaszmurlo requested changes
zamiast owsianki (featured_background.jpg) proponuje wstawic. https://pixabay.com/pl/illustrations/dna-macierz-genetyka-kontroli-3888228/

2020-10-16 11:52 UTC, agaszmurlo commented on .gitlab-ci.yml
> +  #  - tox
czemu toxa wyrzucamy?

2020-10-16 11:52 UTC, agaszmurlo commented on page/config-template.toml
> +url_latest_version = "https://example.com"
tu pewnie trzeba zmienic URL (?)

2020-10-25 17:48 UTC, mwiewior commented on .gitlab-ci.yml
> +  #  - tox
Temporary

2020-10-25 18:05 UTC, merged